#!/bin/bash

progname="bipartite"
output_extension="solved"

if [ ! "$#" -eq 1 ]; then
	echo "$progname filepath.bprtt"
	exit 1
fi

make > /dev/null

if [ ! "$?" -eq 0 ]; then
	echo "[!] Error with make"
	exit 1
fi

if [ ! -f "$1" ] || [ ! -r "$1" ] ; then
	echo "'$1' not a regular file or not readable"	
fi

# Fetch the bytecode executable
elf_prog=$(ls -A1 | grep ftest)

./$elf_prog "$1" "2" "3" "$1.$output_extension"


if [ ! "$?" -eq 0 ]; then
	echo "[!] Error with '$elf_prog'"
	exit 1
fi

# Export the two graphs in SVG format with dot command

inputfilename=$(echo $1 | sed -r "s/.*\/([^/]*$)/\1/g")

dot -Tsvg "$1.dot" > "./graphs/SVGs/$inputfilename.svg"
if [ "$#" -eq 4 ]; then

	outputfilename=$(echo $4 | sed -r "s/.*\/([^/]*$)/\1/g")

	dot -Tsvg "$4.dot" > "./graphs/SVGs/$outputfilename.svg"
	dot -Tsvg "$1.intermediate.dot" > "./graphs/SVGs/$outputfilename.intermediate.svg"

	firefox ./graphs/SVGs/$inputfilename.intermediate.svg ./graphs/SVGs/$outputfilename.svg
else
	dot -Tsvg "$1.$output_extension.dot" > "./graphs/SVGs/$inputfilename.$output_extension.svg"
	dot -Tsvg "$1.intermediate.dot" > "./graphs/SVGs/$inputfilename.intermediate.svg"

	#rm -f ./graphs/$1.$output_extension.dot

	firefox ./graphs/SVGs/$inputfilename.intermediate.svg ./graphs/SVGs/$inputfilename.$output_extension.svg
fi
		
#rm -f ./graphs/*.dot


